import Banco
import DadosBancarios
import Campus
import Espaco
import Polo
import Bloco
import Setor
import Curso
import Disciplina
import Pessoa
import PerfilTipo
import PerfilTipoDocente
import Perfil
import Bolsa
import CursoModalidade
import ServerOpenerp7
import PessoaEndereco
import PessoaContato
