version: "3"

services:
  db:
    image: postgres:9.4
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=odoo
    volumes:
      - "../db_data/:/var/lib/postgresql/data"
      - "../db_backup/:/db_backup/"
  web:
    build: .
    volumes:
      - ".:/src"
    ports:
      - "8069:8069"
      - "8078:8078"
    depends_on:
      - db
