version: "3"

services:
  db:
    image: postgres:9.4
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=odoo
    volumes:
      - "../db_data_odoo10/:/var/lib/postgresql/data"
      - "../db_backup_odoo10/:/db_backup/"
  web:
    build: .
    volumes:
      - ".:/src"
      - "./storage:/root/.local/share/Odoo"
    ports:
      - "8000:8069"
    depends_on:
      - db
