import Anexo
import AreaTrabalho
import Autor
import CategoriaCnpq
import OrientadorTitulacao
import Orientador
import PalavraChave
import Publicacao
import Responsavel
import TipoPublicacao
import Curso_override
